[package]
name = "dx-story-macros"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Procedural macros for dx-story."
license.workspace = true
repository.workspace = true
publish = ["crates-io"]
documentation = "https://docs.rs/dx-story"
keywords = ["dioxus", "storybook", "macros"]
categories = ["development-tools::procedural-macro-helpers", "gui"]
include = ["src/**", "LICENSE"]

[lib]
proc-macro = true

[dependencies]
prettyplease.workspace = true
proc-macro-crate.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[lints]
workspace = true
